### ISSUE TITLE
Can't remove the first empty line in logs

### ISSUE THREAD

**Issue by ewauq** [SergeyPirogov/webdriver_manager#161]
It just a detail by it really bugs me. Even if I choose to show only error logs, there is always an empty line in logs.
The releated code line is [logger.py at line 11](https://github.com/SergeyPirogov/webdriver_manager/blob/master/webdriver_manager/logger.py#L11). Is it possible to prevent this line to be shown? It doesn't break anything, it just prints an empty and useless line in the middle of my logs.

Thank you!

**Comment by VladimirPodolyan** [comment]
Try via `ChromeDriverManager("2.26", print_first_line=False).install()`

**Comment by ewauq** [comment]
The version available from `pip install webdriver-manager` doesn't include the ENV variable. The logger.py file doesn't look like what is on this repo :-/

I tried to reinstall the package with `pip install --upgrade --force-reinstall webdriver_manager` but it doesn't seem to work.

**Comment by vantro** [comment]
Hello
I have the same issue, with a driver installed for the first time today.
Even with the 2 following lines, I still have a blank line in the console.
It is annoying as the automatic process generates an email with nothing inside 
```
os.environ['WDM_LOG_LEVEL'] = '0'
os.environ['WDM_PRINT_FIRST_LINE'] = 'False'
```
Do you have a complementary solution ?

Thank you

**Comment by SergeyPirogov** [comment]
Will fix this early next week

**Comment by SergeyPirogov** [comment]
Fixed in v3.3.0

**Comment by vantro** [comment]
Hello
Even after the update to 3.3.0, I still have the blank line in the console ...
![Capture d’écran 2021-01-25 à 11 42 57](https://user-images.githubusercontent.com/38978744/105696131-31348c00-5f03-11eb-9f12-9f062a8cc2ab.png)

Thanks

**Comment by SergeyPirogov** [comment]
@vantro Is this case for this env parameters?

```
os.environ['WDM_LOG_LEVEL'] = '0'
os.environ['WDM_PRINT_FIRST_LINE'] = 'False'
```

**Comment by vantro** [comment]
Here is the code and the result

```
	os.environ['WDM_LOG_LEVEL'] = '0' 
	os.environ['WDM_PRINT_FIRST_LINE'] = 'False'
	options = webdriver.ChromeOptions()
	prefs = { 
		"download.default_directory": dir,
	 	"download.prompt_for_download": False,
	 	"download.directory_upgrade": True ,
	 	"safebrowsing.enabled": True 
	 	}
	options.add_experimental_option('prefs', prefs)
	options.add_argument('headless')	

	driver = webdriver.Chrome(ChromeDriverManager().install(),options=options)
```
![Capture d’écran 2021-01-25 à 14 01 18](https://user-images.githubusercontent.com/38978744/105709726-64cce180-5f16-11eb-88be-b356837acb55.png)

**Comment by jefferystone** [comment]
I am using WDM 3.7.1 and a blank line does show on the console (not in a log file)
The problem didn't occur when using 3.5.4

**Comment by eyaler** [comment]
@SergeyPirogov can this be reopened?

**Comment by eyaler** [comment]
this is the issue: https://github.com/SergeyPirogov/webdriver_manager/blob/master/webdriver_manager/core/manager.py#L18

**Comment by jefferystone** [comment]
@SergeyPirogov should we open a new Issue if this won't be reopened?

**Comment by eyaler** [comment]
@jefferystone here: https://github.com/SergeyPirogov/webdriver_manager/issues/417
