### ISSUE TITLE
Manager constructor never uses named argument log_level

### ISSUE THREAD

**Issue by TheGenk** [SergeyPirogov/webdriver_manager#167]
# Issue
From the disable logging constructor example in the readme:

```python
ChromeDriverManager("2.26", log_level=0).install()
```

This will never set up the logger with a given `log_level`.  

In [ChromeDriverManager](https://github.com/SergeyPirogov/webdriver_manager/blob/96446bab026f637b9e8433975631b0bec443bc99/webdriver_manager/chrome.py#L11) or its parent [DriverManager](https://github.com/SergeyPirogov/webdriver_manager/blob/96446bab026f637b9e8433975631b0bec443bc99/webdriver_manager/manager.py#L9) can see this variable is never used.

I expect logic should exist at the `DriverManager` to handle this for all managers.  With out this feature; the only way to disable logging is via environmental variable or running hacky code to create a logger in `loggers`

## Workaround 1 - environment variable
Set  WDM_LOG_LEVEL to '0'

## Workaround 2 - hacky loggers manipulation
```python
# Call this before executing any WDM functionality
def disable_wdm_logger():
    from webdriver_manager.logger import loggers as _loggers
    _log = logging.getLogger('WDM')
    _loggers['WDM'] = _log
    _log.addHandler(logging.NullHandler())


disable_wdm_logger()
```

**Comment by DanielOberlechner** [comment]
Hi,
i had the exact same issue as you did, and therefore I simply tried to use the environment variable and it did suddenly work.
Still this is a ugly bug and should be fixed by the package maintainer.

Kind regards,
by Daniel :)

**Comment by aleksandr-kotlyar** [comment]
> Hi,
> i had the exact same issue as you did, and therefore I simply tried to use the environment variable and it did suddenly work.
> Still this is a ugly bug and should be fixed by the package maintainer.
> 
> Kind regards,
> by Daniel :)

It should be fixed in https://github.com/SergeyPirogov/webdriver_manager/pull/170 - hadn't it @DanielOberlechner ? If not - what version of wdm do you use? :)

**Comment by DanielOberlechner** [comment]
@aleksandr-kotlyar 
I used the actual version on that day, and there it wasn't fixed.
Should be the following:
webdriver-manager  3.4.2
