### ISSUE TITLE
Google renamed Mac M1 zipfile and downloads no longer work

### ISSUE THREAD

**Issue by chingc** [SergeyPirogov/webdriver_manager#446]
I recently updated Chrome and suddenly webdriver manager started failing downloads.

It seems that Google renamed their mac m1 zipfiles from `chromedriver_mac64_m1.zip` to `chromedriver_mac_arm64.zip` starting with [ChromeDriver 106.0.5249.61](https://chromedriver.storage.googleapis.com/index.html?path=106.0.5249.61/).

```resp = <Response [404]>

    @staticmethod
    def validate_response(resp: requests.Response):
        status_code = resp.status_code
        if status_code == 404:
>           raise ValueError(f"There is no such driver by url {resp.url}")
E           ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/106.0.5249.61/chromedriver_mac64_m1.zip

.venv/lib/python3.9/site-packages/webdriver_manager/core/http.py:15: ValueError
```

**Comment by JohnThomas-at** [comment]
I was able to temporarily work around this by commenting out line 31 and 32 in `webdriver_manager/drivers/chrome.py` 

```
        # if is_arch(os_type):
        #     return f"{os_type.replace('_m1', '')}_m1"
```

and passing in the correct value for os_type to `ChromeDriverManager`:

```
driver = webdriver.Chrome(service=ChromeService(ChromeDriverManager(os_type="mac_arm64").install()))
```

Definitely not a long term fix but got me unblocked for some quick testing I needed to do.

**Comment by pauldambra** [comment]
Fix is merged here https://github.com/SergeyPirogov/webdriver_manager/pull/445

(although I don't know when it will be released??)

**Comment by pauldambra** [comment]
see https://github.com/SergeyPirogov/webdriver_manager/issues/443

**Comment by pauldambra** [comment]
@SergeyPirogov I appreciate open source can be a thankless task with randoms from the internet making demands but.... :)

Do you know when you'll release a version including #445? Mostly so I can set how frequently I check 

(also thank you for the library!)

**Comment by cmin764** [comment]
I'm waiting as well for a next release @SergeyPirogov including this fix. We're relying on it under [rpaframework](https://pypi.org/project/rpaframework/) used by [Robocorp](https://robocorp.com/).

**Comment by jfuruness** [comment]
This is still broken in the latest release on M1 mac

**Comment by chrisgraham24** [comment]
> 

I tried this work-around, but no luck...is there anything else I need to do?

**Comment by flukestar** [comment]
Also broken on M2 mac

I used @JohnThomas-at solution to get it working for now

**Comment by patolj2** [comment]
> Also broken on M2 mac
> 
> I used @JohnThomas-at solution to get it working for now

me too, thanks for @JohnThomas-at

**Comment by Coedice** [comment]
According to Sergey's profile, he's lives in Kiev, Ukraine. Completely understandable to not be doing GitHub stuff. I hope you and your family are well Sergey.

**Comment by pauldambra** [comment]
This being such an issue for us @posthog prompted me to add @SergeyPirogov to our open source sponsorship https://posthog.com/handbook/growth/marketing/open-source-sponsorship

We ❤️ open source and I hadn't realised how much we'd come to depend on this library

Is there other help people can offer?

**Comment by SergeyPirogov** [comment]
Sorry guys. It's not the best time for Ukraine now to do open source, especially when Russia shelling Kyiv and other cities. I am happy to add anyone of you as a maintainer for this project. Just leave your Github ids and let me know that you are ready to contribute.

**Comment by pauldambra** [comment]
Hey @SergeyPirogov 

My colleague https://github.com/benjackwhite and myself https://github.com/pauldambra are happy to volunteer to help out

**Comment by SergeyPirogov** [comment]
@pauldambra I've sent invites. Let me know if something wrong

**Comment by ysparrow** [comment]
> According to Sergey's profile, he lives in Kiev, Ukraine. Completely understandable to not be doing GitHub stuff. I hope you and your family are well Sergey.

Kyiv, not Kiev. Please.

**Comment by jfuruness** [comment]
Hey @SergeyPirogov

I hope all is well. My github is https://github.com/jfuruness/ and I'd love to contribute as well if you still would like help.

Thanks.
Justin

**Comment by chrisgraham24** [comment]
3.8.4 did not fix the issue for me.

**Comment by Coedice** [comment]
@chrisgraham24 The patch has been merged, but the patched version has not yet been released. 3.8.4 is the latest released version, but it does not include the patch yet.

**Comment by pauldambra** [comment]
Hey @Coedice @chrisgraham24 I've just checked the diff and v3.8.4 includes the fix https://github.com/SergeyPirogov/webdriver_manager/compare/v3.8.3...v3.8.4

And has fixed the problem for us in https://github.com/PostHog/posthog/pull/12325

Are you still seeing errors? What errors do you see after upgrading?

**Comment by Coedice** [comment]
Hi @pauldambra, my mistake, I thought I updated to the latest version, but that didn't seem to be the case. I was still on v3.8.3. Just tested, all is working well now.

**Comment by pauldambra** [comment]
resolved in v3.8.4

**Comment by chrisgraham24** [comment]
I am still getting this: "ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/107.0.5304.62/chromedriver_mac64_m1.zip"

**Comment by pauldambra** [comment]
@chrisgraham24 that's the "old" style URL for the chrome driver. (sorry to ask a possibly silly question but...) are you sure you're on 3.8.4?

**Comment by chrisgraham24** [comment]
Weird...yes, I just confirmed I am on 3.8.4. Maybe I need to do a full uninstall and clean install? Can someone tell me the correct steps to do that? I would appreciate it. Thanks

**Comment by robcerda** [comment]
Would love to be able to contribute to this. Github @robcerda
