### ISSUE TITLE
ChromeDriverManager: No module named 'packaging'

### ISSUE THREAD

**Issue by PFython** [SergeyPirogov/webdriver_manager#460]
Hi buddy - first of all THANK YOU for creating a really helpful package.  Version 3.8.3 still works smoothly for me but I'm getting the following error when using version 3.8.4 with Selenium 4.5.0 and Windows 10:

```
    from webdriver_manager.chrome import ChromeDriverManager
  File "C:\Users\peter\AppData\Roaming\Python\Python310\site-packages\webdriver_manager\chrome.py", line 7, in <module>
    from webdriver_manager.drivers.chrome import ChromeDriver
  File "C:\Users\peter\AppData\Roaming\Python\Python310\site-packages\webdriver_manager\drivers\chrome.py", line 1, in <module>
    from packaging import version
ModuleNotFoundError: No module named 'packaging'
```
I'm using the boiler-plate from your README, namely:

```
# selenium 4
from selenium import webdriver
from selenium.webdriver.chrome.service import Service as ChromeService
from webdriver_manager.chrome import ChromeDriverManager

driver = webdriver.Chrome(service=ChromeService(ChromeDriverManager().install()))
```

**Comment by fstafforini** [comment]
I have met with this bug too, using the same code. Installing the packaging module solves the error:
pip install packaging 

I suppose there must be an error in the package, shouldn't this have been installed automatically when installing webdriver_manager?

**Comment by pawel-lesniak** [comment]
I encountered it also after updating webdriver-manager to 3.8.4

**Comment by IvelinGushkov** [comment]
This is discussed in #454 and fixed in #455 
As temporary fix you could manually install 'packaging' until the new version is released.

**Comment by PttCodingMan** [comment]
Still missing packaging in pypi version.

https://pypi.org/project/webdriver-manager/3.8.4/#files

![image](https://user-images.githubusercontent.com/59732316/199663429-97bd5192-510e-4b9a-8f7b-7282b623ef94.png)

**Comment by aleksandr-kotlyar** [comment]
Fixed in 3.8.5 release.
