### ISSUE TITLE
Fails on 64 bit Windows machine

### ISSUE THREAD

**Issue by JJ-in-Jersey** [SergeyPirogov/webdriver_manager#554]
install package
in python console in Pycharm running on Windows 64bit machine using Windows 10 enterprise:
     from webdriver_manager.chrome import ChromeDriverManager
     ChromeDriverManager().install()

generates the following error:
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.3.1\plugins\python-ce\helpers\pydev\pydevconsole.py", line 364, in runcode
    coro = func()
           ^^^^^^
  File "<input>", line 1, in <module>
  File "C:\Users\XXXXXXXX\AppData\Local\Programs\Python\Python311\Lib\site-packages\webdriver_manager\chrome.py", line 39, in install
    driver_path = self._get_driver_binary_path(self.driver)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXXXXXXX\AppData\Local\Programs\Python\Python311\Lib\site-packages\webdriver_manager\core\manager.py", line 33, in _get_driver_binary_path
    file = self._download_manager.download_file(driver.get_driver_download_url())
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXXXXXXX\AppData\Local\Programs\Python\Python311\Lib\site-packages\webdriver_manager\drivers\chrome.py", line 59, in get_driver_download_url
    modern_version_url = self.get_url_for_version_and_platform(driver_version_to_download, os_type)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXXXXXXX\AppData\Local\Programs\Python\Python311\Lib\site-packages\webdriver_manager\drivers\chrome.py", line 94, in get_url_for_version_and_platform
    raise Exception(f"No such driver version {browser_version} for {platform}")
Exception: No such driver version 115.0.5790.99 for win32

**Comment by studioj** [comment]
although im struggling with similar issues, it seems like most peoples issues got solved by updating to 3.9.1

**Comment by JJ-in-Jersey** [comment]
I did upgrade and it didn’t fix it. I suspect it’s that there isn’t a separate 32 bit driver

**Comment by SergeyPirogov** [comment]
Official Selenium Docs says that you can upgrade to the latest Selenium version and it will manage drivers by itself

**Comment by limarman** [comment]
What does this mean for windows 64-bit users? That we cannot continue using this tool?

**Comment by JJ-in-Jersey** [comment]
I can’t comment on the implications. I posted the way I can reproduce it. I was hoping someone more familiar with the actual code sort out the problem
